### ISSUE TITLE
PR Elementary Circuits Algorithm

### ISSUE THREAD

**Issue by Volker-Weissmann** [PrototypeRailGun/graphalgs#2]
There exists an [algorithm for finding all elementary circuits in a directed graph](https://www.cs.tufts.edu/comp/150GA/homeworks/hw1/Johnson%2075.PDF). I need said algorithm for a project of mine, and afaik there is no rust implementation of it. I have two options:

1. Implement the algorithm for myself, then move on.
2. Implement the algorithm properly, write documentation  and tests, then create a PR in this repo.

Do you think I should do the first or the second option? Would you merge such a PR?

**Comment by starovoid** [comment]
I am glad to welcome you! Personally, I would choose the second option, because it's a good contribution to the community and a great success for those who will look for this algorithm in the future. And of course, I will merge such pull request.

**Comment by starovoid** [comment]
Thank you so much for contribution. Your algorithm is now available as graphalgs::elementary_circuits::elementary_circuits()

**Comment by Volker-Weissmann** [comment]
Thank you for merging. Also, maybe you should run `cargo clippy` and look at the reports.
